version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.35.0
  - dependency-name: ts-loader
    versions:
    - 9.0.0
    - 9.1.0
