name: Build and Deploy to Github pages

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: yarn

      - name: Deploy to Github Pages
        run: |
          git config --global user.email ${{ secrets.access_github_email }}
          git config --global user.name ${{ secrets.access_github_username }}
          git remote set-url origin https://${{ secrets.access_token }}@github.com/flsy/react-mapycz
          yarn deploy